### ISSUE TITLE
XML error: class attribute is required for feat

### ISSUE THREAD

**Issue by naiaden** [proycon/tscan#1]
While parsing the bible (each sentence on a new line and wc bijbel.txt =
  33779  761332 4220718), I get the following error:
working dir /tmp/tscan-20137/
opened file input/bijbel.txt
FoLiaParsing failed:
XML error: class attribute is required for feat
Segmentation fault

And all the output files are empty.

I've tried turning the parsers off, but that does not change anything. 

[config.txt](https://github.com/proycon/tscan/files/467122/config.txt)
[errorlog.txt](https://github.com/proycon/tscan/files/467124/errorlog.txt)

**Comment by mhkuu** [comment]
Thanks for reporting @naiaden. This seems to be a problem in Frog (generates invalid FoLiA on some input), that should be resolved when the newest version is released to the server. I'll close this issue when this has been done.

**Comment by proycon** [comment]
I just released and deployed the new Frog (v0.13.5), hopefully that should fix it then?

**Comment by naiaden** [comment]
Nope, I still get the same segfault with frog 0.13.6 and TScan 0.3.

**Comment by mhkuu** [comment]
That's unfortunate! I'll have a look and see if I can maybe circumvent this problem in T-Scan.

**Comment by kosloot** [comment]
Or switch off --deep-morph if possible 
Don't think Louis needs it
Ko


Verzonden vanaf Samsung Mobile.

<div>-------- Oorspronkelijk bericht --------</div><div>Van: Martijn <notifications@github.com> </div><div>Datum:14-09-2016  15:28  (GMT+01:00) </div><div>Aan: proycon/tscan <tscan@noreply.github.com> </div><div>Onderwerp: Re: [proycon/tscan] XML error: class attribute is required for feat
  (#1) </div><div>
</div>That's unfortunate! I'll have a look and see if I can maybe circumvent this problem in T-Scan.

**Comment by mhkuu** [comment]
@naiaden Could you try again? I've followed up on @kosloot's suggestion to switch --deep-morph off for the moment.

**Comment by naiaden** [comment]
Both the command line and the server do not work.
The error.log shows that there's a different error: Segmentation fault
At least it's _some_ progress ;)



[config1.txt](https://github.com/proycon/tscan/files/487282/config1.txt)
[errorlog1.txt](https://github.com/proycon/tscan/files/487284/errorlog1.txt)

**Comment by mhkuu** [comment]
Can you attach your input file?

**Comment by naiaden** [comment]
Sure: https://oje.home.xs4all.nl/txt/bijbel/Het-Boek.txt

**Comment by mhkuu** [comment]
The text doesn't seem to process when I turn off the Alpino parser. This is a bug, but with the Alpino parser things work fine and you'll get more sensible output.

**Comment by naiaden** [comment]
There is also a bug when Alpino is enabled:

```
Entity: line 1: parser error : Start tag expected, '<' not found
Error: fadd_error([126,119,32,40,101,114,114,111,114,32,110,111,58,32,126,119,41
^
alpino parser failed!
done with Alpino Server
analyse tokenized sentence=2 : Laat uit de vier hoeken van het altaar horens steken en overtrek dan het hele altaar met koper .
calling Alpino Server

XML-error: Start tag expected, '<' not found

alpino parser failed!
done with Alpino Server
Segmentation fault
```

[config3.txt](https://github.com/proycon/tscan/files/492817/config3.txt)
[errorlog3.txt](https://github.com/proycon/tscan/files/492818/errorlog3.txt)

**Comment by kosloot** [comment]
Ok,
ik draai dit nu op mijn lokale t-scan (de Git versies van alles)
Het-Boek groeit uit tot een XML van > 21 Gb, en dan kan mijn PC het niet
meer aan.
Geen idee hoe groot het uiteindlijk wordt. En of de servers het aankunnen.


On 09/26/2016 12:18 PM, naiaden wrote:
> There is also a bug when Alpino is enabled:
> 
> |Entity: line 1: parser error : Start tag expected, '<' not found Error:
> fadd_error([126,119,32,40,101,114,114,111,114,32,110,111,58,32,126,119,41 ^
> alpino parser failed! done with Alpino Server analyse tokenized
> sentence=2 : Laat uit de vier hoeken van het altaar horens steken en
> overtrek dan het hele altaar met koper . calling Alpino Server
> XML-error: Start tag expected, '<' not found alpino parser failed! done
> with Alpino Server Segmentation fault |
> 
> config3.txt <https://github.com/proycon/tscan/files/492817/config3.txt>
> errorlog3.txt <https://github.com/proycon/tscan/files/492818/errorlog3.txt>
> 

Ik heb losse stukjes geprobeerd, ook van exodus 27 en dan gaat alles goed.
Misschien is het een idee om te splitsen per boek(deel)

Ko

**Comment by mhkuu** [comment]
Hoi Ko, 
Dat splitsen lijkt me inderdaad een goede suggestie; dan maak ik wel een issue aan om een maximale grootte voor geuploade bestanden aan te houden.

**Comment by kosloot** [comment]
On 09/28/2016 01:07 PM, Martijn wrote:
> Hoi Ko,
> Dat splitsen lijkt me inderdaad een goede suggestie; dan maak ik wel een
> issue aan om een maximale grootte voor geuploade bestanden aan te houden.

Wat geen garantie is dat het dan wel goed gaat.
Maar debuggen wordt wel simpeler.
Overigens is Het-Boek een " ISO-8859 text, with very long lines, with
CRLF line terminators"
naiden: Converteren naar UTF8 is sowieso nodig

Ko

**Comment by kosloot** [comment]
Nog even ingaand op die fadd_error([126,119,32,40,101,114,114,111,114,32,110,111,58,32,126,119,41 ..
Daat staat dus:
fadd_error( ~w (error no:~w...
Prolog wil ons iets vertellen, maar wat.....
