### ISSUE TITLE
Wopr not functioning

### ISSUE THREAD

**Issue by mhkuu** [proycon/tscan#12]
Wopr returns _ERROR: exception caught: No Document ID specified_. T-Scan shows _No usable FoLia date retrieved from Wopr. Got ''_. 

Not sure what happens. Something wrong in the input to Wopr?

**Comment by kosloot** [comment]
OK, this is caused by updates in libfolia. 
I will patch wopr accordingly.

**Comment by kosloot** [comment]
fixed. @proycon please update wopr on the servers!

**Comment by proycon** [comment]
Done! Can we do a wopr release? (otherwise it will revert back to the last stable on LaMachine update)

**Comment by kosloot** [comment]
wopr 1.41 is released
