### ISSUE TITLE
Paragraphs not recognised

### ISSUE THREAD

**Issue by joepfranssen** [proycon/tscan#14]
The T-scan works great again! Only one thing is not clear to me yet.

I have a number of reviews that I would like to regard as a paragraph. Every review is already in line with an enter in between so I hoped that they would be considered separate sections. However, he turns the entire document into one paragraph when I view the output.

Do you see what I am doing wrong? I want the average number of letters per word, words per sentence, etc. per observation (i.e. review) (remaining 400 features).

That does not work, even if I set split per line to yes or if I remove the blank lines. I also tried the bare text as input, but then unfortunately it also failed to get it per paragraph.

Thanks for your help!
[groupaveragefinal3.txt](https://github.com/proycon/tscan/files/3892345/groupaveragefinal3.txt)

![output](https://user-images.githubusercontent.com/57620058/69643293-6de8c700-1063-11ea-85f4-69b9fff5b581.png)

**Comment by kosloot** [comment]
This is odd. Tscan creates 1 paragraph indeed.
When I feed this file directly to Frog, multiple paragraphs are created.
Running Frog is the first step taken by Tscan. So I am quite puzzled now.
Must have to do with some odd setting.
Needs investigating....

**Comment by kosloot** [comment]
Well... When feeding this file to the Frog SERVER, only one paragraph is created. So this must some regression in Frog.
I created a Frog issue: https://github.com/LanguageMachines/frog/issues/84

**Comment by joepfranssen** [comment]
Hi Ko, thanks for your reply and for creating the issue. When do you expect to do the investigation? Then I will try attune my schedule to it :)

**Comment by kosloot** [comment]
Investigation is on his way. But maybe it  is even not a Frog problem but something in Ucto.
Hunting it down, stay tuned :)

**Comment by kosloot** [comment]
The web-service seems to work correct again.
