### ISSUE TITLE
Publish formal stable releases for tscan

### ISSUE THREAD

**Issue by proycon** [proycon/tscan#4]
I'd like to propose to regularly publish stable releases through github for tscan. This is not just good practise in general, but it makes deployment easier as well. It should be as easy as filling https://github.com/proycon/tscan/releases/new: use something like v0.3 for release tag/title and bump the version in ``configure.ac`` after release.

Right now I encountered a LaMachine failure because we rely on the master branch for tscan, having no releases; currently the master branch relies on libfolia 1.6 but this is bleeding-edge development and not released yet, so the build fails on the stable LaMachine now. Recall that LaMachine has two flavours, it grabs either the latest releases or the git master branch, the installation in Nijmegen is following the former for stability and ease of maintenance.

**Comment by proycon** [comment]
We may first want to do a release prior to commit b85c69b213251e0f9b9f5f42ffa78e2fd4ef9187  ? Or are the new libfolia and frog ready for release as well?

**Comment by mhkuu** [comment]
Hi @proycon and @kosloot , good point. I'll have a look at this later this week (hopefully).

**Comment by kosloot** [comment]
Releasing is quite simple, and provides you with a  DOI for referencing

**Comment by mhkuu** [comment]
Yes, it turned out to be simpler than I thought, I had made releases for Python projects before but wasn't sure about the correct flow for C++ projects :-)
