### ISSUE TITLE
reading datafiles might randomly crash...

### ISSUE THREAD

**Issue by kosloot** [proycon/tscan#6]
nouns_semtype.data may have entries with 3 or 6 columns:
```
winkelconcept	nondynamic	1	concept	winkel	2
woonconcept	nondynamic	1	concept	woon	2
anticonceptie	nondynamic	0			
aluminiumconcern	institut	1	concern	aluminium	2
autoconcern	institut	1	concern	auto	2
```
But the code in filNN happily assumes all are 6 columns:
```
    // Classify the noun, set the compound values and add the noun to the map
    noun n;
    n.type = SEM::classifyNoun(parts[1]);
    n.is_compound = parts[2] == "1";
    if (n.is_compound) {
      n.head = parts[3];
      n.satellite_clean = parts[4];
      n.compound_parts = atoi(parts[5].c_str());
    }
    m[parts[0]] = n;
```

This must lead to problems (and does so on my PC)
a few line earlier, the 3 column case is explicitly allowed!
```
    if (i != 3 && i != 6) {
      cerr << "skip line: " << line << " (expected 3 or 6 values, got " << i << ")" << endl;
      continue;
    }
```

**Comment by mhkuu** [comment]
Thanks a lot @kosloot . Is it OK if I take a look at this after the Easter break?

**Comment by kosloot** [comment]
No problem!
nice holidays, and see you next week @susans promotion

**Comment by mhkuu** [comment]
Hi @kosloot, should be fixed now, there were some errors in the _nouns_semtype.data_ file unfortunately, so if you download the data file again, things should work again.

**Comment by kosloot** [comment]
Still unclear how/were to get these restricted files :{
