### ISSUE TITLE
certain restricted datafiles cannot be read, causing tscan to error

### ISSUE THREAD

**Issue by Duchadian** [proycon/tscan#7]
(lamachine-lm-dev) duchs@duchsserver:Documents$ tscan testfile 
TScan 0.9.1
working dir /tmp/tscan-1252/
couldn't open file: adjs_semtype.data

### after commenting out that file in the config

(lamachine-lm-dev) duchs@duchsserver:Documents$ tscan testfile 
TScan 0.9.1
working dir /tmp/tscan-1260/
couldn't open file: nouns_semtype.data

### commenting out adj_semtypes and noun_semtypes in the config makes tscan start

(lamachine-lm-dev) duchs@duchsserver:Documents$ tscan testfile 
TScan 0.9.1
working dir /tmp/tscan-1264/
read data/freqlist_staphorsius_CLIB_words.freq (192912 entries)
read data/freqlist_staphorsius_CLIB_words.freq (192912 entries)
read data/freqlist_staphorsius_CLIB_lemma.freq (195779 entries)
opened file testfile

Strangely enough, verb_semtypes doesn't need to be commented out for tscan to start, even though it is empty like the other two files. Other empty files do not seem to cause errors.

**Comment by mhkuu** [comment]
Thanks for reporting, this is because we allow custom files for nouns_semtype and adjs_semtype. Because of that, the config needs the full path. Fixed this in the example configuration file.
