### ISSUE TITLE
startup scripts for webservices fail in some instances

### ISSUE THREAD

**Issue by Duchadian** [proycon/tscan#8]
As the title says, the startup scripts fail in some instances (mostly when the scripts are run via ssh it seems). 

I'll take .startfrog.sh as an example. 

The cause of the failure seems to be re-interpretation of the PORT variable from 7001 to 7  1, to '7', '', '1' when called with ${PORT}. This seems to be an issue central to bash.

This results in the last line ( frog -X --id=${ID} -c ${CONFIG} --skip=mp -S${PORT} 2> $LOGFILE ) interpreting 7 as the port, with '' and '1' being seen as files for frog to parse. The other scripts do not fail as spectacularly, yet raise errors because they all try to occupy the same port (7). 

The workaround seems to be to quote the variables in question (i.e. change ${PORT} to "${PORT}").

**Comment by Duchadian** [comment]
This issue was also reported to @proycon and @kosloot, just thought I should put it here for reference.

**Comment by proycon** [comment]
Neither I nor Ko could reproduce it though, and we find it a very weird spooky issue :)

**Comment by mhkuu** [comment]
This is solved through #9 right? Please re-open if not :-)
